DATA:
  TYPE: "cot"
  BATCH_SIZE: 32
  EVAL_BATCH_SIZE: 1
  STEP_BY_STEP:
    METHOD: 'few_shot_cot'
    MAX_LENGTH_COT: 256
  FEW_SHOT_COT_PROMPT: False
  TRAIN: "TRAIN"
  TEST: "VALID"
  LIMIT_DATASET_SIZE: -1
  SHUFFLE_COT_PROMPTS: True
  RANDOM_DROP_COT_PROMPTS: False
  RANDOM_DROP_COT_PROMPTS_MIN_NUM: 3
  PROMPT_ARGS:
    USE_DATASET: True
    PREDICT_RATIONALE: True
    PROMPT_RATIONALE: True
    LOAD_RATIONALES: True
  FILTER_STRATEGY: all_correct_paths_balanced
  OVERRIDE_CONFIG: configs_data/complete/_prompts.py

TRAIN:
  SAMPLE_INTERVAL: -1
  TOTAL_STEPS: 20000
  EVAL_INTERVAL: 2000
  SAVE_INTERVAL: 2000
  GRAD_ACCUMULATE_STEPS: 1
  LR: 2e-5
  CLIP_GRAD: True
  DATAPOOL_PATH: "DATAPOOL/test.json"

MODEL:
  TYPE: "api"
  NAME: "gpt3-xl"
  ADDITIONL_SUFFIX_STRING: "\n\n"
  STOP_TOKEN_GPT: "\n\n"

POLICY_MODEL:
  TYPE: "auto"
  NAME: "facebook/opt-1.3b" #"facebook/opt-6.7b" 350m 2.7b 1.3b
  LOAD_WITH_ACCELERATE: True
  STOP_AT_NEW_LINE: True
  LOAD_WITH_FP16: False
  # ACCELERATE_MAX_MEMORY: ( ("cpu", "50GB"), (0, "40GB"), (1, "40GB"), )
  USE_QUARK: False
  REWARD_CATEGORY_NUM: 2
  POOL_THRESHOLD: 0.5
  STOP_AT_NEW_LINE_BATCHED: True
  MAX_INPUT_LENGTH: 700